### ISSUE TITLE
Tools - All pages does not work

### ISSUE THREAD

**Issue by achimwessling** [claudioc/jingo#83] opened 2015-06-19 12:15 UTC
In my installation I get an empty result when calling Tools - All pages. I'm using the current version (1.2.11) on iojs! Any hint is welcome! Thanks!

**Comment by claudioc** [comment] 2015-06-28 09:35
Hi, Unfortunately I am not able to reproduce this problem on my installation(s). I never tested Jingo with io.js, though. Which version of io are you using?

**Comment by achimwessling** [comment] 2015-06-28 13:15
I use iojs 2.3.1. I switched from nodejs to iojs, because I got an error  during the installation of jingo when npm tries to load the dependencies. If I remember it correctly it was a dependency of iconv, which won't install properly under windows.

**Comment by achimwessling** [comment] 2015-07-21 14:28
Today I updatet to version 1.3.0. I still get an empty result when calling Tools - All pages.
How can I support you find this problem / error?

**Comment by achimwessling** [comment] 2015-09-08 05:38
I could solve the problem on my system with the changes in the following commit: https://github.com/achimwessling/jingo/commit/2324dbbad8b6d0c7f60ab2d3d80374dd9a97a698!

I'm on window$ and I'm not a very experienced git user! So I'm not really sure what's the difference of both?

**Comment by brad7928** [comment] 2015-12-14 01:21
This could be closed? [io.js has merged with the Node.js project again as of Node v4.](https://iojs.org/en/)

**Comment by Lichtjaeger** [comment] 2016-03-01 14:17
Same here using Node v5.7 on Windows.

Removing `, "--", docSubdir + pattern ` from `ls` in gitmech.js helping here too.

**Closed** 2017-05-20 17:49 UTC
